-- Seed the canonical 80-parameter catalog used by the API, worker, and mobile app.
INSERT INTO "ParameterCatalog" ("id", "canonicalName", "aliases", "unit", "panel", "rangeDefault", "criticalLow", "criticalHigh")
VALUES
  ('hemoglobin', 'Hemoglobin', ARRAY['Hb', 'HGB']::TEXT[], 'g/dL', 'Complete Blood Count (CBC)', '{"default":null,"bySex":{"male":{"min":13.5,"max":17.5},"female":{"min":12,"max":15.5}}}'::JSONB, NULL, NULL),
  ('total-rbc-count', 'Total RBC Count', ARRAY['RBC']::TEXT[], 'million/µL', 'Complete Blood Count (CBC)', '{"default":null,"bySex":{"male":{"min":4.7,"max":6.1},"female":{"min":4.2,"max":5.4}}}'::JSONB, NULL, NULL),
  ('hematocrit-pcv', 'Hematocrit / PCV', ARRAY['HCT', 'PCV']::TEXT[], '%', 'Complete Blood Count (CBC)', '{"default":null,"bySex":{"male":{"min":41,"max":53},"female":{"min":36,"max":46}}}'::JSONB, NULL, NULL),
  ('mcv', 'Mean Corpuscular Volume', ARRAY['MCV']::TEXT[], 'fL', 'Complete Blood Count (CBC)', '{"default":{"min":80,"max":100}}'::JSONB, NULL, NULL),
  ('mch', 'Mean Corpuscular Hemoglobin', ARRAY['MCH']::TEXT[], 'pg', 'Complete Blood Count (CBC)', '{"default":{"min":27,"max":33}}'::JSONB, NULL, NULL),
  ('mchc', 'MCH Concentration', ARRAY['MCHC']::TEXT[], 'g/dL', 'Complete Blood Count (CBC)', '{"default":{"min":32,"max":36}}'::JSONB, NULL, NULL),
  ('total-wbc-count', 'Total WBC Count', ARRAY['WBC', 'TLC', 'Leukocytes']::TEXT[], 'cells/µL', 'Complete Blood Count (CBC)', '{"default":{"min":4000,"max":11000}}'::JSONB, NULL, NULL),
  ('platelet-count', 'Platelet Count', ARRAY['PLT']::TEXT[], 'cells/µL', 'Complete Blood Count (CBC)', '{"default":{"min":150000,"max":450000}}'::JSONB, NULL, NULL),
  ('neutrophils', 'Neutrophils (Differential)', ARRAY['NEUT%']::TEXT[], '%', 'Complete Blood Count (CBC)', '{"default":{"min":40,"max":70}}'::JSONB, NULL, NULL),
  ('lymphocytes', 'Lymphocytes (Differential)', ARRAY['LYMPH%']::TEXT[], '%', 'Complete Blood Count (CBC)', '{"default":{"min":20,"max":45}}'::JSONB, NULL, NULL),
  ('total-cholesterol', 'Total Cholesterol', ARRAY['TC', 'Cholesterol']::TEXT[], 'mg/dL', 'Lipid Profile', '{"default":{"min":null,"max":200}}'::JSONB, NULL, NULL),
  ('ldl-cholesterol', 'LDL Cholesterol', ARRAY['LDL-C', 'LDL']::TEXT[], 'mg/dL', 'Lipid Profile', '{"default":{"min":null,"max":100}}'::JSONB, NULL, NULL),
  ('hdl-cholesterol', 'HDL Cholesterol', ARRAY['HDL-C', 'HDL']::TEXT[], 'mg/dL', 'Lipid Profile', '{"default":null,"bySex":{"male":{"min":40,"max":null},"female":{"min":50,"max":null}}}'::JSONB, NULL, NULL),
  ('triglycerides', 'Triglycerides', ARRAY['TG', 'TGL']::TEXT[], 'mg/dL', 'Lipid Profile', '{"default":{"min":null,"max":150}}'::JSONB, NULL, NULL),
  ('vldl-cholesterol', 'VLDL Cholesterol', ARRAY['VLDL']::TEXT[], 'mg/dL', 'Lipid Profile', '{"default":{"min":5,"max":40}}'::JSONB, NULL, NULL),
  ('total-hdl-ratio', 'Total / HDL Ratio', ARRAY['TC:HDL']::TEXT[], 'ratio', 'Lipid Profile', '{"default":{"min":null,"max":5}}'::JSONB, NULL, NULL),
  ('total-bilirubin', 'Total Bilirubin', ARRAY['T.Bil']::TEXT[], 'mg/dL', 'Liver Function Test (LFT)', '{"default":{"min":0.1,"max":1.2}}'::JSONB, NULL, NULL),
  ('direct-bilirubin', 'Direct Bilirubin', ARRAY['D.Bil', 'Conjugated']::TEXT[], 'mg/dL', 'Liver Function Test (LFT)', '{"default":{"min":0,"max":0.3}}'::JSONB, NULL, NULL),
  ('indirect-bilirubin', 'Indirect Bilirubin', ARRAY['I.Bil', 'Unconjugated']::TEXT[], 'mg/dL', 'Liver Function Test (LFT)', '{"default":{"min":0.1,"max":0.9}}'::JSONB, NULL, NULL),
  ('ast-sgot', 'AST / SGOT', ARRAY['AST', 'SGOT']::TEXT[], 'U/L', 'Liver Function Test (LFT)', '{"default":{"min":null,"max":40}}'::JSONB, NULL, NULL),
  ('alt-sgpt', 'ALT / SGPT', ARRAY['ALT', 'SGPT']::TEXT[], 'U/L', 'Liver Function Test (LFT)', '{"default":{"min":null,"max":45}}'::JSONB, NULL, NULL),
  ('alkaline-phosphatase', 'Alkaline Phosphatase', ARRAY['ALP']::TEXT[], 'U/L', 'Liver Function Test (LFT)', '{"default":{"min":44,"max":147}}'::JSONB, NULL, NULL),
  ('gamma-gt', 'Gamma GT', ARRAY['GGT']::TEXT[], 'U/L', 'Liver Function Test (LFT)', '{"default":null,"bySex":{"male":{"min":8,"max":61},"female":{"min":5,"max":36}}}'::JSONB, NULL, NULL),
  ('total-protein', 'Total Protein', ARRAY['TP']::TEXT[], 'g/dL', 'Liver Function Test (LFT)', '{"default":{"min":6,"max":8.3}}'::JSONB, NULL, NULL),
  ('serum-albumin', 'Serum Albumin', ARRAY['Albumin']::TEXT[], 'g/dL', 'Liver Function Test (LFT)', '{"default":{"min":3.5,"max":5}}'::JSONB, NULL, NULL),
  ('serum-creatinine', 'Serum Creatinine', ARRAY['Creatinine', 'Cr']::TEXT[], 'mg/dL', 'Kidney Function Test (KFT)', '{"default":null,"bySex":{"male":{"min":0.7,"max":1.3},"female":{"min":0.6,"max":1.1}}}'::JSONB, NULL, NULL),
  ('blood-urea-nitrogen', 'Blood Urea Nitrogen', ARRAY['BUN']::TEXT[], 'mg/dL', 'Kidney Function Test (KFT)', '{"default":{"min":7,"max":20}}'::JSONB, NULL, NULL),
  ('blood-urea', 'Blood Urea', ARRAY['Urea']::TEXT[], 'mg/dL', 'Kidney Function Test (KFT)', '{"default":{"min":15,"max":45}}'::JSONB, NULL, NULL),
  ('uric-acid', 'Uric Acid', ARRAY['UA']::TEXT[], 'mg/dL', 'Kidney Function Test (KFT)', '{"default":null,"bySex":{"male":{"min":3.4,"max":7},"female":{"min":2.4,"max":6}}}'::JSONB, NULL, NULL),
  ('egfr', 'eGFR (Estimated GFR)', ARRAY['eGFR', 'GFR']::TEXT[], 'mL/min/1.73m²', 'Kidney Function Test (KFT)', '{"default":{"min":90,"max":null}}'::JSONB, NULL, NULL),
  ('serum-calcium', 'Serum Calcium', ARRAY['Ca']::TEXT[], 'mg/dL', 'Kidney Function Test (KFT)', '{"default":{"min":8.5,"max":10.5}}'::JSONB, NULL, NULL),
  ('serum-phosphorus', 'Serum Phosphorus', ARRAY['PO4']::TEXT[], 'mg/dL', 'Kidney Function Test (KFT)', '{"default":{"min":2.5,"max":4.5}}'::JSONB, NULL, NULL),
  ('tsh', 'Thyroid Stimulating Hormone', ARRAY['TSH']::TEXT[], 'µIU/mL', 'Thyroid Profile', '{"default":{"min":0.4,"max":4}}'::JSONB, NULL, NULL),
  ('free-t3', 'Free T3', ARRAY['FT3']::TEXT[], 'pg/mL', 'Thyroid Profile', '{"default":{"min":2.3,"max":4.2}}'::JSONB, NULL, NULL),
  ('free-t4', 'Free T4', ARRAY['FT4']::TEXT[], 'ng/dL', 'Thyroid Profile', '{"default":{"min":0.8,"max":1.8}}'::JSONB, NULL, NULL),
  ('total-t3', 'Total T3', ARRAY['T3']::TEXT[], 'ng/dL', 'Thyroid Profile', '{"default":{"min":80,"max":200}}'::JSONB, NULL, NULL),
  ('total-t4', 'Total T4', ARRAY['T4']::TEXT[], 'µg/dL', 'Thyroid Profile', '{"default":{"min":5.1,"max":14.1}}'::JSONB, NULL, NULL),
  ('fasting-blood-glucose', 'Fasting Blood Glucose', ARRAY['FBS', 'FPG']::TEXT[], 'mg/dL', 'Diabetes Panel', '{"default":{"min":70,"max":99}}'::JSONB, NULL, NULL),
  ('postprandial-blood-glucose', 'Postprandial Blood Glucose', ARRAY['PPBS', '2-hr PG']::TEXT[], 'mg/dL', 'Diabetes Panel', '{"default":{"min":null,"max":140}}'::JSONB, NULL, NULL),
  ('random-blood-sugar', 'Random Blood Sugar', ARRAY['RBS']::TEXT[], 'mg/dL', 'Diabetes Panel', '{"default":{"min":null,"max":200}}'::JSONB, NULL, NULL),
  ('hba1c', 'HbA1c (Glycated Hemoglobin)', ARRAY['HbA1c', 'A1C']::TEXT[], '%', 'Diabetes Panel', '{"default":{"min":null,"max":5.7}}'::JSONB, NULL, NULL),
  ('fasting-insulin', 'Fasting Insulin', ARRAY['Insulin']::TEXT[], 'µU/mL', 'Diabetes Panel', '{"default":{"min":2.6,"max":24.9}}'::JSONB, NULL, NULL),
  ('vitamin-d', 'Vitamin D (25-OH)', ARRAY['Vit D', '25-OH-D']::TEXT[], 'ng/mL', 'Vitamin & Mineral Panel', '{"default":{"min":30,"max":100}}'::JSONB, NULL, NULL),
  ('vitamin-b12', 'Vitamin B12', ARRAY['B12', 'Cobalamin']::TEXT[], 'pg/mL', 'Vitamin & Mineral Panel', '{"default":{"min":200,"max":900}}'::JSONB, NULL, NULL),
  ('folate', 'Folate (Folic Acid)', ARRAY['Folate', 'B9']::TEXT[], 'ng/mL', 'Vitamin & Mineral Panel', '{"default":{"min":2.7,"max":17}}'::JSONB, NULL, NULL),
  ('serum-iron', 'Serum Iron', ARRAY['Iron', 'Fe']::TEXT[], 'µg/dL', 'Vitamin & Mineral Panel', '{"default":null,"bySex":{"male":{"min":65,"max":175},"female":{"min":50,"max":170}}}'::JSONB, NULL, NULL),
  ('ferritin', 'Ferritin', ARRAY['Ferritin']::TEXT[], 'ng/mL', 'Vitamin & Mineral Panel', '{"default":null,"bySex":{"male":{"min":24,"max":336},"female":{"min":11,"max":307}}}'::JSONB, NULL, NULL),
  ('tibc', 'TIBC', ARRAY['Total Iron Binding Capacity']::TEXT[], 'µg/dL', 'Vitamin & Mineral Panel', '{"default":{"min":240,"max":450}}'::JSONB, NULL, NULL),
  ('magnesium', 'Magnesium', ARRAY['Mg']::TEXT[], 'mg/dL', 'Vitamin & Mineral Panel', '{"default":{"min":1.7,"max":2.2}}'::JSONB, NULL, NULL),
  ('urine-ph', 'Urine pH', ARRAY['pH']::TEXT[], '', 'Urine Routine', '{"default":{"min":4.5,"max":8}}'::JSONB, NULL, NULL),
  ('urine-specific-gravity', 'Urine Specific Gravity', ARRAY['SG']::TEXT[], '', 'Urine Routine', '{"default":{"min":1.005,"max":1.03}}'::JSONB, NULL, NULL),
  ('urine-protein', 'Urine Protein', ARRAY['Albumin (urine)']::TEXT[], 'qualitative', 'Urine Routine', '{"default":null,"qualitativeNormal":"Negative / Trace"}'::JSONB, NULL, NULL),
  ('urine-glucose', 'Urine Glucose', ARRAY['Glycosuria']::TEXT[], 'qualitative', 'Urine Routine', '{"default":null,"qualitativeNormal":"Negative"}'::JSONB, NULL, NULL),
  ('urine-ketones', 'Urine Ketones', ARRAY['Ketones']::TEXT[], 'qualitative', 'Urine Routine', '{"default":null,"qualitativeNormal":"Negative"}'::JSONB, NULL, NULL),
  ('urine-microalbumin', 'Urine Microalbumin', ARRAY['Microalbumin']::TEXT[], 'mg/L', 'Urine Routine', '{"default":{"min":null,"max":30}}'::JSONB, NULL, NULL),
  ('troponin-i', 'Troponin I', ARRAY['TnI', 'cTnI']::TEXT[], 'ng/mL', 'Cardiac Markers', '{"default":{"min":null,"max":0.04}}'::JSONB, NULL, NULL),
  ('ck-mb', 'CK-MB', ARRAY['Creatine Kinase MB']::TEXT[], 'ng/mL', 'Cardiac Markers', '{"default":{"min":null,"max":5}}'::JSONB, NULL, NULL),
  ('total-cpk', 'Total CPK', ARRAY['CK', 'CPK']::TEXT[], 'U/L', 'Cardiac Markers', '{"default":null,"bySex":{"male":{"min":39,"max":308},"female":{"min":26,"max":192}}}'::JSONB, NULL, NULL),
  ('hs-crp', 'hs-CRP', ARRAY['High-sensitivity CRP']::TEXT[], 'mg/L', 'Cardiac Markers', '{"default":{"min":null,"max":1}}'::JSONB, NULL, NULL),
  ('bnp', 'BNP / NT-proBNP', ARRAY['BNP', 'proBNP']::TEXT[], 'pg/mL', 'Cardiac Markers', '{"default":{"min":null,"max":100}}'::JSONB, NULL, NULL),
  ('serum-sodium', 'Serum Sodium', ARRAY['Na+']::TEXT[], 'mEq/L', 'Electrolytes', '{"default":{"min":135,"max":145}}'::JSONB, NULL, NULL),
  ('serum-potassium', 'Serum Potassium', ARRAY['K+']::TEXT[], 'mEq/L', 'Electrolytes', '{"default":{"min":3.5,"max":5}}'::JSONB, NULL, NULL),
  ('serum-chloride', 'Serum Chloride', ARRAY['Cl-']::TEXT[], 'mEq/L', 'Electrolytes', '{"default":{"min":98,"max":107}}'::JSONB, NULL, NULL),
  ('serum-bicarbonate', 'Serum Bicarbonate', ARRAY['HCO3-']::TEXT[], 'mEq/L', 'Electrolytes', '{"default":{"min":22,"max":28}}'::JSONB, NULL, NULL),
  ('systolic-bp', 'Systolic Blood Pressure', ARRAY['SBP']::TEXT[], 'mmHg', 'Vitals', '{"default":{"min":null,"max":120}}'::JSONB, NULL, NULL),
  ('diastolic-bp', 'Diastolic Blood Pressure', ARRAY['DBP']::TEXT[], 'mmHg', 'Vitals', '{"default":{"min":null,"max":80}}'::JSONB, NULL, NULL),
  ('resting-heart-rate', 'Resting Heart Rate', ARRAY['HR', 'Pulse']::TEXT[], 'bpm', 'Vitals', '{"default":{"min":60,"max":100}}'::JSONB, NULL, NULL),
  ('body-temperature', 'Body Temperature', ARRAY['Temp']::TEXT[], '°F', 'Vitals', '{"default":{"min":97,"max":99}}'::JSONB, NULL, NULL),
  ('body-weight', 'Body Weight', ARRAY['Weight']::TEXT[], 'kg', 'Vitals', '{"default":null}'::JSONB, NULL, NULL),
  ('height', 'Height', ARRAY['Ht']::TEXT[], 'cm', 'Vitals', '{"default":null}'::JSONB, NULL, NULL),
  ('bmi', 'Body Mass Index', ARRAY['BMI']::TEXT[], 'kg/m²', 'Vitals', '{"default":{"min":18.5,"max":24.9}}'::JSONB, NULL, NULL),
  ('waist-circumference', 'Waist Circumference', ARRAY['WC']::TEXT[], 'cm', 'Vitals', '{"default":null,"bySex":{"male":{"min":null,"max":94},"female":{"min":null,"max":80}}}'::JSONB, NULL, NULL),
  ('spo2', 'SpO2 (Oxygen Saturation)', ARRAY['SpO2', 'O2 Sat']::TEXT[], '%', 'Vitals', '{"default":{"min":95,"max":100}}'::JSONB, NULL, NULL),
  ('esr', 'ESR', ARRAY['Erythrocyte Sedimentation Rate']::TEXT[], 'mm/hr', 'Additional Common Markers', '{"default":null,"bySex":{"male":{"min":0,"max":15},"female":{"min":0,"max":20}}}'::JSONB, NULL, NULL),
  ('crp', 'C-Reactive Protein', ARRAY['CRP']::TEXT[], 'mg/L', 'Additional Common Markers', '{"default":{"min":null,"max":10}}'::JSONB, NULL, NULL),
  ('psa', 'PSA (Total)', ARRAY['PSA']::TEXT[], 'ng/mL', 'Additional Common Markers', '{"default":{"min":null,"max":4}}'::JSONB, NULL, NULL),
  ('beta-hcg', 'Beta hCG', ARRAY['hCG']::TEXT[], 'mIU/mL', 'Additional Common Markers', '{"default":{"min":null,"max":5}}'::JSONB, NULL, NULL),
  ('non-hdl-cholesterol', 'Random Cholesterol (LDL/HDL Calc)', ARRAY['Non-HDL Cholesterol']::TEXT[], 'mg/dL', 'Additional Common Markers', '{"default":{"min":null,"max":130}}'::JSONB, NULL, NULL),
  ('pp-tg', 'Random Triglycerides Post-Meal', ARRAY['PP-TG']::TEXT[], 'mg/dL', 'Additional Common Markers', '{"default":{"min":null,"max":175}}'::JSONB, NULL, NULL),
  ('random-glucose-capillary', 'Random Glucose (Capillary)', ARRAY['SMBG']::TEXT[], 'mg/dL', 'Additional Common Markers', '{"default":{"min":80,"max":180}}'::JSONB, NULL, NULL)
ON CONFLICT ("canonicalName") DO UPDATE SET
  "id" = EXCLUDED."id",
  "aliases" = EXCLUDED."aliases",
  "unit" = EXCLUDED."unit",
  "panel" = EXCLUDED."panel",
  "rangeDefault" = EXCLUDED."rangeDefault",
  "criticalLow" = EXCLUDED."criticalLow",
  "criticalHigh" = EXCLUDED."criticalHigh";
