// Public doctor-share view (server component). Phase 0 placeholder — the real
// scoped medical summary + server-rendered charts arrive in Phase 5. Fetches
// the public share endpoint and renders a stub.

const API_URL = process.env.DOCTOR_SHARE_API_URL ?? 'http://localhost:3000';

async function fetchShare(token: string): Promise<{ ok: boolean }> {
  try {
    const res = await fetch(`${API_URL}/public/share/${encodeURIComponent(token)}`, {
      cache: 'no-store',
    });
    return { ok: res.ok };
  } catch {
    return { ok: false };
  }
}

export default async function SharePage({ params }: { params: { token: string } }) {
  // We intentionally don't render the token or any fetched PHI yet.
  await fetchShare(params.token);

  return (
    <main style={{ maxWidth: 720, margin: '0 auto', padding: '3rem 1.5rem' }}>
      <h1 style={{ color: '#1F4E79' }}>Medical Tracker</h1>
      <p>Share view coming in Phase 5.</p>
      <p style={{ color: '#5C6B7A', fontSize: 14 }}>
        Generated by Medical Tracker. This is a copy of records submitted by the patient and is not
        a diagnostic document.
      </p>
    </main>
  );
}
