import type { PublicShareView } from '@medical-tracker/shared-types';

const API_URL = process.env.DOCTOR_SHARE_API_URL ?? 'http://localhost:3000';

const FLAG_COLORS: Record<string, string> = {
  normal: '#2E7D32',
  low: '#1565C0',
  high: '#E65100',
  critical: '#B71C1C',
  unknown: '#5C6B7A',
};

const FLAG_LABELS: Record<string, string> = {
  normal: 'Normal',
  low: 'Low',
  high: 'High',
  critical: 'Critical',
  unknown: '—',
};

async function fetchShare(token: string): Promise<PublicShareView | null> {
  try {
    const res = await fetch(
      `${API_URL}/public/share/${encodeURIComponent(token)}`,
      { cache: 'no-store' },
    );
    if (!res.ok) return null;
    return res.json() as Promise<PublicShareView>;
  } catch {
    return null;
  }
}

export default async function SharePage({ params }: { params: { token: string } }) {
  const view = await fetchShare(params.token);

  if (!view) {
    return (
      <main style={s.main}>
        <Header />
        <div style={s.errorBox}>
          <h2 style={{ margin: 0, color: '#B71C1C' }}>Link unavailable</h2>
          <p style={{ margin: '8px 0 0', color: '#5C6B7A' }}>
            This share link may have expired, been revoked, or already used.
          </p>
        </div>
      </main>
    );
  }

  return (
    <main style={s.main}>
      <Header />

      {/* Patient summary card */}
      <section style={s.card}>
        <h2 style={s.cardTitle}>Patient</h2>
        <dl style={s.dl}>
          <Row label="First name" value={view.patient.firstName} />
          <Row label="Age" value={view.patient.ageBand} />
          <Row label="Sex" value={view.patient.sex} />
          {view.patient.bloodGroup && (
            <Row label="Blood group" value={view.patient.bloodGroup} />
          )}
        </dl>
      </section>

      {/* Custom note */}
      {view.customNote && (
        <section style={{ ...s.card, background: '#FFF8E1', borderColor: '#F9A825' }}>
          <p style={{ margin: 0, color: '#5C4033', fontSize: 14 }}>
            <strong>Note from patient:</strong> {view.customNote}
          </p>
        </section>
      )}

      {/* Parameters */}
      {view.parameters.length > 0 && (
        <section style={s.card}>
          <h2 style={s.cardTitle}>Lab Parameters</h2>
          {view.parameters.map((param) => (
            <div key={param.canonical} style={s.paramBlock}>
              <div style={s.paramHeader}>
                <span style={s.paramName}>{param.canonical}</span>
                <span style={s.paramMeta}>
                  {param.unit} · Normal: {param.normalRange}
                </span>
              </div>
              <table style={s.table}>
                <thead>
                  <tr>
                    <th style={s.th}>Date</th>
                    <th style={s.th}>Value</th>
                    <th style={s.th}>Flag</th>
                  </tr>
                </thead>
                <tbody>
                  {param.readings.map((r, i) => {
                    const flag = r.rangeFlag.toLowerCase();
                    const color = FLAG_COLORS[flag] ?? FLAG_COLORS.unknown;
                    return (
                      <tr key={i} style={i % 2 === 0 ? s.trEven : {}}>
                        <td style={s.td}>{r.date}</td>
                        <td style={s.td}>
                          {r.value} {param.unit}
                        </td>
                        <td style={{ ...s.td, color, fontWeight: 600 }}>
                          {FLAG_LABELS[flag] ?? r.rangeFlag}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          ))}
        </section>
      )}

      {/* Documents */}
      {view.documents.length > 0 && (
        <section style={s.card}>
          <h2 style={s.cardTitle}>Documents</h2>
          {view.documents.map((doc, i) => (
            <div key={i} style={s.docRow}>
              <div>
                <span style={s.docType}>{doc.docType.replace(/_/g, ' ')}</span>
                <span style={s.docDate}>{doc.sourceDate}</span>
              </div>
            </div>
          ))}
        </section>
      )}

      <footer style={s.footer}>
        Generated by Medical Tracker. This is a copy of records submitted by the patient
        and is not a diagnostic document.
      </footer>
    </main>
  );
}

function Header() {
  return (
    <div style={s.header}>
      <h1 style={s.headerTitle}>Medical Tracker</h1>
      <span style={s.headerSub}>Shared health summary</span>
    </div>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <>
      <dt style={s.dt}>{label}</dt>
      <dd style={s.dd}>{value}</dd>
    </>
  );
}

const s: Record<string, React.CSSProperties> = {
  main: { maxWidth: 760, margin: '0 auto', padding: '2rem 1.25rem', fontFamily: 'inherit' },
  header: { marginBottom: '1.5rem', borderBottom: '2px solid #1F4E79', paddingBottom: '0.75rem' },
  headerTitle: { margin: 0, color: '#1F4E79', fontSize: 24 },
  headerSub: { fontSize: 13, color: '#5C6B7A' },
  card: {
    background: '#fff',
    border: '1px solid #DEE5EC',
    borderRadius: 8,
    padding: '1.25rem',
    marginBottom: '1rem',
  },
  cardTitle: { margin: '0 0 0.75rem', fontSize: 15, fontWeight: 700, color: '#1F4E79', textTransform: 'uppercase', letterSpacing: 0.5 },
  errorBox: {
    background: '#FFF5F5',
    border: '1px solid #FFCDD2',
    borderRadius: 8,
    padding: '1.5rem',
  },
  dl: { display: 'grid', gridTemplateColumns: '140px 1fr', gap: '4px 0', margin: 0 },
  dt: { fontWeight: 600, color: '#5C6B7A', fontSize: 13, padding: '3px 0' },
  dd: { margin: 0, color: '#1A1A1A', fontSize: 14, padding: '3px 0' },
  paramBlock: { marginBottom: '1.25rem', paddingBottom: '1.25rem', borderBottom: '1px solid #DEE5EC' },
  paramHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: '0.5rem' },
  paramName: { fontWeight: 600, fontSize: 14, color: '#1A1A1A' },
  paramMeta: { fontSize: 12, color: '#5C6B7A' },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: 13 },
  th: { textAlign: 'left', padding: '5px 8px', color: '#5C6B7A', fontWeight: 600, fontSize: 12, borderBottom: '1px solid #DEE5EC' },
  td: { padding: '5px 8px', color: '#1A1A1A' },
  trEven: { background: '#F7F9FC' },
  docRow: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '8px 0', borderBottom: '1px solid #DEE5EC' },
  docType: { fontWeight: 600, fontSize: 14, color: '#1A1A1A', textTransform: 'capitalize', marginRight: 12 },
  docDate: { fontSize: 13, color: '#5C6B7A' },
  footer: { marginTop: '2rem', fontSize: 12, color: '#8A9BB0', textAlign: 'center' },
};
